CREATE EXTERNAL TABLE `mfw_dwd.fact_flow_mobile_hpinfo_event_increment`(
   `device_id` string comment '设备ID',
   `uid` bigint comment '用户ID',
   `u_loc_mdd_id` bigint comment '用户目的地ID',
   `sys_ver` string comment '系统版本号',
   `device_brand` string comment '设备品牌',
   `device_model` string comment '设备型号',
   `device_token` string comment '设备推送码',
   `device_type` string comment '设备类型',
   `app_ver` string comment '客户端版本号',
   `net_type` bigint comment '网络类型',
   `channel_origin` string comment '安装渠道',
   `channel_code` string comment '升级渠道',
   `client_ip` string comment '客户端IP',
   `service_ip` string comment '服务端IP',
   `isp` string comment '网络服务运营商',
   `sdk_ver` string comment 'SDK版本',
   `mfw_env` string comment '客户端环境',
   `service_time` timestamp comment '服务端时间戳',
   `service_hour` string comment '服务端小时',
   `launch_guid` string comment '启动唯一ID',
   `day_first` bigint comment '距第一次启动的天数',
   `day_before` bigint comment '距上一次启动的天数',
   `lat` double comment '纬度',
   `lng` double comment '经度',
   `city` string comment '城市',
   `province` string comment '省',
   `event_time` timestamp comment '事件时间',
   `event_guid` string comment '事件ID',
   `event_code` string comment '事件名称',
   `channel_id` bigint comment '频道ID',
   `dutarion` double comment '停留时长',
   `is_ad` bigint comment '是否有广告',  --往后加字段
   `item_id` string comment '内容ID',
   `group_item_id` string comment '组内容id', --2
   `item_business_id` string comment '内容业务id',
   `group_business_id` string comment '组内容业务id',
   `model_id` string comment '资源位ID',
   `author_id` string comment '作者uid',
   `module_name` string comment '模块名称',
   `item_title` string comment '内容标题',
   `item_type` string comment '内容类型',
   `abtest_type` string comment 'abtest类型',
   `abtest` string comment 'abtest内容',
   `group_abtest_type` string comment '组abtest类型',
   `group_abtest` string comment '组abtest内容',
   `is_default` string comment '是否默认展示频道',
   `is_in` string comment '是否吸顶',
   `refresh_type` string comment '刷新类型',
   `refresh_range` string comment '刷新范围',
   `index_page` bigint comment '加载页数',
   `load_num` bigint comment '加载内容条数',
   `item_source` string comment '元素类别',
   `item_url` string comment '内容share_jump',
   `item_uri` string comment '资源链接',
   `item_index` bigint comment '内容索引',
   `group_index` bigint comment '组的内容索引',
   `pic_index` bigint comment '大图索引',
   `page_index` bigint comment '页数索引',
   `extra` string comment '额外信息',
   `group_extra` string comment '组额外信息',
   `page_name` string comment '页面名称',
   `page_guid` string comment '页面唯一ID',
   `parent_page_guid` string comment '父页面唯一ID',
   `parent_uri` string comment '父URI',
   `uri` string comment 'URI',
   `referer_uri` string comment '上一页URI',
   `trigger_level` bigint comment '访问层级',
   `parent_name`  string comment '父页面名称',
   `trigger_path` string comment '触发点路径',
   `trigger_point` string comment '触发点',
   `parent_url` string comment '父页面URL',
   `app_code` string comment '客户端APP标识',
   `dimession1` string,
   `dimession2` string,
   `dimession3` string,
   `dimession4` string,
   `dimession5` string,
   `dimession6` string,
   `dimession7` string,
   `dimession8` string,
   `dimession9` string,
   `dimession10` string,
   `dimession11` timestamp,
   `dimession12` double,
   `dimession13` bigint,
   `dimession14` array<string>,
   `dimession15` map<string,string>,
   `dimession16` timestamp,
   `dimession17` double,
   `dimession18` bigint,
   `dimession19` array<string>,
   `dimession20` map<string,string>
  )comment '流量移动端首页信息流事件表'
PARTITIONED BY (`dt` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
  tblproperties('create_owner'='liusengen','modify_owner'='liusengen');
